name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: jira-description-action
        uses: cakeinpanic/jira-description-action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_URL }}
          skip-branches: '^(production-release|main|master|release\/v\d+)$'
          fail-when-jira-issue-not-found: false
          use: both
